-- DDL

--CREATE TABLE "USER"
--(
--    ID       INTEGER PRIMARY KEY,
--    NAME     VARCHAR(64),
--    EMAIL    VARCHAR(64),
--    PASSWORD VARCHAR(64)
--);

CREATE TABLE IF NOT EXISTS CLIENT
(
    ID       INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(64),
    EMAIL    VARCHAR(64) UNIQUE,
    PASSWORD VARCHAR(64),
    CARD     VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(64),
    EMAIL      VARCHAR(64) UNIQUE,
    PASSWORD   VARCHAR(64),
    DEPARTMENT VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ORDERS
(
    ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE   INTEGER,
    CLIENT     INTEGER,
    APPROVED   BOOLEAN,
    CONSTRAINT FK_EMPNO FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE (ID),
    CONSTRAINT FK_CLNO FOREIGN KEY (CLIENT) REFERENCES CLIENT (ID)
);

CREATE TABLE IF NOT EXISTS MANUFACTURER
(
    ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS APPLIANCE
(
    ID              INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME            VARCHAR(64),
    CATEGORY        VARCHAR(5),
    MODEL           VARCHAR(64),
    MANUFACTURER_ID INTEGER,
    POWER_TYPE      VARCHAR(11),
    CHARACTERISTIC  VARCHAR(512),
    DESCRIPTION     VARCHAR(1024),
    POWER           INTEGER,
    PRICE           DOUBLE,
    CONSTRAINT FK_MANNO FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ROW
(
    ID         INTEGER PRIMARY KEY AUTO_INCREMENT,
    APPLIANCE  INTEGER,
    NUMBER     INTEGER,
    AMOUNT     DOUBLE,
    ORDERS     INTEGER,
    CONSTRAINT FK_APPNO FOREIGN KEY (APPLIANCE) REFERENCES APPLIANCE (ID),
    CONSTRAINT FK_ORDNO FOREIGN KEY (ORDERS) REFERENCES ORDERS (ID)
);

COMMIT;
